spring.application.name=ureca-bookKOK

#MySql 데이터베이스 연결 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bookkokdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

spring.config.import=optional:application-local.properties

#JAP 테이블 자동 생성 및 SQL 로그 출력 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Spring Security 필터 체인 상세 로그 확인
logging.level.org.springframework.security=DEBUG

#jwt 암호화키
jwt.secret=bookkokSecretKeyForJwtAuthentication2026ProjectVerySecureKey

#카카오 API연동
kakao.client-id=62f4228bd2b51bf2f39dec36373333e0
kakao.client-secret=4JBWsIcowVtzUF7dLQakLYk75MdXqWbo
kakao.redirect-uri=http://localhost:8080/login/kakao/auth-code
